[2023-12-08T22:15:32.797+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Zillow_Dag.load_file_to_s3 manual__2023-12-08T22:15:23.570088+00:00 [queued]>
[2023-12-08T22:15:32.804+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Zillow_Dag.load_file_to_s3 manual__2023-12-08T22:15:23.570088+00:00 [queued]>
[2023-12-08T22:15:32.805+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-12-08T22:15:32.820+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): load_file_to_s3> on 2023-12-08 22:15:23.570088+00:00
[2023-12-08T22:15:32.824+0000] {standard_task_runner.py:57} INFO - Started process 24463 to run task
[2023-12-08T22:15:32.830+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Zillow_Dag', 'load_file_to_s3', 'manual__2023-12-08T22:15:23.570088+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmph5f5z3y2']
[2023-12-08T22:15:32.832+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask load_file_to_s3
[2023-12-08T22:15:32.870+0000] {task_command.py:416} INFO - Running <TaskInstance: Zillow_Dag.load_file_to_s3 manual__2023-12-08T22:15:23.570088+00:00 [running]> on host ip-172-31-29-175.eu-north-1.compute.internal
[2023-12-08T22:15:33.053+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='anamsken60@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Zillow_Dag' AIRFLOW_CTX_TASK_ID='load_file_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T22:15:23.570088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-08T22:15:23.570088+00:00'
[2023-12-08T22:15:33.054+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-08T22:15:33.055+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv /home/ubuntu/response_data_08122023221529.json s3://zillow-analytics-ec2/lagos/']
[2023-12-08T22:15:33.062+0000] {subprocess.py:86} INFO - Output:
[2023-12-08T22:15:33.064+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: aws: command not found
[2023-12-08T22:15:33.064+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-08T22:15:33.073+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-08T22:15:33.076+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Zillow_Dag, task_id=load_file_to_s3, execution_date=20231208T221523, start_date=20231208T221532, end_date=20231208T221533
[2023-12-08T22:15:33.093+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task load_file_to_s3 (Bash command failed. The command returned a non-zero exit code 127.; 24463)
[2023-12-08T22:15:33.125+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-08T22:15:33.140+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
