[2023-12-08T22:17:45.270+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Zillow_Dag.load_file_to_s3 manual__2023-12-08T22:13:29.145912+00:00 [queued]>
[2023-12-08T22:17:45.280+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Zillow_Dag.load_file_to_s3 manual__2023-12-08T22:13:29.145912+00:00 [queued]>
[2023-12-08T22:17:45.280+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-12-08T22:17:45.301+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): load_file_to_s3> on 2023-12-08 22:13:29.145912+00:00
[2023-12-08T22:17:45.305+0000] {standard_task_runner.py:57} INFO - Started process 25229 to run task
[2023-12-08T22:17:45.309+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Zillow_Dag', 'load_file_to_s3', 'manual__2023-12-08T22:13:29.145912+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpvgacehhz']
[2023-12-08T22:17:45.311+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask load_file_to_s3
[2023-12-08T22:17:45.354+0000] {task_command.py:416} INFO - Running <TaskInstance: Zillow_Dag.load_file_to_s3 manual__2023-12-08T22:13:29.145912+00:00 [running]> on host ip-172-31-29-175.eu-north-1.compute.internal
[2023-12-08T22:17:45.521+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='anamsken60@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Zillow_Dag' AIRFLOW_CTX_TASK_ID='load_file_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T22:13:29.145912+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-08T22:13:29.145912+00:00'
[2023-12-08T22:17:45.522+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-08T22:17:45.523+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv /home/ubuntu/response_data_08122023221336.json s3://zillow-analytics-ec2/lagos/']
[2023-12-08T22:17:45.529+0000] {subprocess.py:86} INFO - Output:
[2023-12-08T22:17:45.530+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: aws: command not found
[2023-12-08T22:17:45.531+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-08T22:17:45.540+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-08T22:17:45.545+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Zillow_Dag, task_id=load_file_to_s3, execution_date=20231208T221329, start_date=20231208T221745, end_date=20231208T221745
[2023-12-08T22:17:45.562+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task load_file_to_s3 (Bash command failed. The command returned a non-zero exit code 127.; 25229)
[2023-12-08T22:17:45.601+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-08T22:17:45.615+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
